Sentinel
smartcontractkit/chainlink-testing-framework pull request #1469
Opened 2024-12-10 17:09 UTC by davidcauchi

2024-12-11 12:07 UTC, skudasov requested changes

2024-12-11 12:07 UTC, skudasov commented on sentinel/README.md
> +## Table of Contents
I really want to test it with testnets before we merge, at least `Fuji`, `Sepolia`, some `Optimism` and `Arbitrum`

2024-12-12 09:32 UTC, davidcauchi commented on sentinel/.changeset/v1.50.1.md
> +- Sentinel init
Done

2024-12-16 10:45 UTC, gheorghestrimtu approved these changes

2024-12-18 12:58 UTC, merged