update remote runner to work with a specific name
smartcontractkit/chainlink-testing-framework pull request #881
Opened 2024-03-26 20:50 UTC by AnieeG

2024-03-26 21:04 UTC, tateexon approved these changes

2024-04-11 17:45 UTC, AnieeG commented on k8s/environment/environment.go
> +			m.AddChart(DataFromRunner(&Props{
added this pod to enable accessing reports once remote runner job gets completed

2024-04-11 17:48 UTC, kalverra requested changes

2024-04-11 17:48 UTC, kalverra commented on k8s/environment/environment.go
> +func (m *Environment) CopyFromPod(selector, containerName, srcPath, destPath string) error {
Function comment please

2024-04-11 17:48 UTC, kalverra commented on k8s/environment/environment.go
> +func (m *Environment) CopyToPod(selector, containerName, srcPath, destPath string) error {
Anotha one

2024-04-11 22:04 UTC, kalverra approved these changes

2024-04-12 05:31 UTC, merged